[package]
name = "sparsey"
version = "0.1.0"
authors = ["Tudor-Cristian Lechintan <lechintantudor02@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1"
downcast-rs = "1"
paste = "1"
rayon = "1"

[[example]]
name = "simple_system"
path = "examples/e01_simple_system.rs"

[[example]]
name = "components"
path = "examples/e02_components.rs"
