[package]
name = "ecstasy"
version = "0.1.0"
authors = ["Tudor Lechintan <lechintantudor02@gmail.com>"]
edition = "2018"

[dependencies]
parking_lot = "0.11"
paste = "1.0"

[[example]]
name = "test"
path = "examples/test.rs"

[[example]]
name = "test2"
path = "examples/test2.rs"
