[package]
name = "sparsey"
version = "0.1.0"
authors = ["Tudor-Cristian Lechintan <lechintantudor02@gmail.com>"]
edition = "2018"

[features]
default = ["parallel"]
parallel = ["rayon"]

[dependencies]
anyhow = "1"
atomic_refcell = "0.1.7"
bitflags = "1"
downcast-rs = "1"
paste = "1"

rayon = { version = "1", optional = true }

[dev-dependencies]
rayon = "1"
