[package]
name = "ecstasy"
version = "0.1.0"
authors = ["Tudor Lechintan <lechintantudor02@gmail.com>"]
edition = "2018"

[dependencies]
atomic_refcell = "0.1"
bitflags = "1"
downcast-rs = "1"
paste = "1"
rayon = "1"

[[example]]
name = "sparse-set"
path = "examples/sparse_set.rs"

[[example]]
name = "world"
path = "examples/world.rs"
